apiVersion: v1
kind: Service
metadata:
  name: {{ include "vuejs-ver2-chart.fullname" . }}
  labels:
    {{- include "vuejs-ver2-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 82
      protocol: TCP
      name: http
  selector:
    {{- include "vuejs-ver2-chart.selectorLabels" . | nindent 4 }}
